language: go
go:
  - 1.13.x

os:
  - linux
  - osx

dist: trusty
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - go build
  - go test
  - ./ncgo tcping -host www.baidu.com
  - ./ncgo httpstat -u https://www.baidu.com/
  - ./ncgo httpstat -u  https://www.baidu.com:443/
  - ./ncgo httpstat -X POST -d 'post' -u  https://httpbin.org/post
  - ./ncgo httpstat -X DELETE -u  https://httpbin.org/delete
  - ./ncgo httpstat  -u https://www.google.com/
  - ./ncgo httpstat  -u https://www.google.com:443/
  - ./ncgo httpstat -L  -u https://httpbin.org/redirect-to?url=https://httpbin.org/relative-redirect/1
  - ./ncgo httpstat -I  -u https://httpbin.org/headers
  - ./ncgo httpstat -I -L  -u http://httpbin.org/redirect/1
  - ./ncgo httpstat  -u https://www.apple.com/
  - ./ncgo httpstat -H Accept:\ application/vnd.heroku+json\;\ version=3  -u https://api.heroku.com/schema
#  - ./ncgo httpstat -O  -u http://example.com/file && stat file
#  - ./ncgo httpstat -o custom  -u http://example.com/file && stat custom
  - ./ncgo httpstat -O  -u https://httpbin.org/response-headers?Content-Disposition=attachment%3B%20filename%3dtest.json && stat test.json
  - ./ncgo httpstat -u  google.com
  - ./ncgo httpstat -u google.com:80
  - ./ncgo httpstat -u google.com:443
  - ./ncgo httpstat -u golang.org:80/dl
  - ./ncgo httpstat -u  golang.org:443/dl
  - ./ncgo httpstat -u  https://http2.akamai.com/
#  - ./ncgo httpstat -H Host:\ www.google.com  -u https://$(dig +short www.google.com | head -1):443/
