language: go
go:
  - master
os:
  - linux
dist: trusty # 编译的操作系统是 ubuntu trusty
sudo: false
install: true
env:
  - GO111MODULE=on
  - VERSION=$(cat VERSION)
  - APPNAME=ncgo
script:
  - go build
  - go test
  - "./ncgo tcping -host www.baidu.com"
  - "./ncgo httpstat -u https://www.baidu.com/"
  - "./ncgo httpstat -u  https://www.baidu.com:443/"
  - "./ncgo httpstat -X POST -d 'post' -u  https://httpbin.org/post"
  - "./ncgo httpstat -X DELETE -u  https://httpbin.org/delete"
  - "./ncgo httpstat  -u https://www.google.com/"
  - "./ncgo httpstat  -u https://www.google.com:443/"
  - "./ncgo httpstat -L  -u https://httpbin.org/redirect-to?url=https://httpbin.org/relative-redirect/1"
  - "./ncgo httpstat -I  -u https://httpbin.org/headers"
  - "./ncgo httpstat -I -L  -u http://httpbin.org/redirect/1"
  - "./ncgo httpstat  -u https://www.apple.com/"
  - "./ncgo httpstat -H Accept:\\ application/vnd.heroku+json\\;\\ version=3  -u https://api.heroku.com/schema"
  - "./ncgo httpstat -O  -u https://httpbin.org/response-headers?Content-Disposition=attachment%3B%20filename%3dtest.json
  && stat test.json"
  - "./ncgo httpstat -u  google.com"
  - "./ncgo httpstat -u google.com:80"
  - "./ncgo httpstat -u google.com:443"
  - "./ncgo httpstat -u golang.org:80/dl"
  - "./ncgo httpstat -u  golang.org:443/dl"
  - "./ncgo httpstat -u  https://http2.akamai.com/"
before_deploy:
  - GO111MODULE=on GOOS=linux  GOARCH=amd64 go build -o $APPNAME-v$VERSION-linux-amd64
  - GO111MODULE=on GOOS=darwin GOARCH=amd64 go build -o $APPNAME-v$VERSION-darwin-amd64
  - GO111MODULE=on GOOS=windows GOARCH=amd64 go build -o $APPNAME-v$VERSION-windows-amd64.exe
notifications:
  email:
    - licoolgo@gmail.com
deploy:
  provider: releases
  api_key:
    secure: gNNeaw3EZRAPDq29EhxK83K5b1ZBnW7lYwQ0gPAsjnWQf3bM5ucfMryzz19xw3GSLDf6TnjUvHTAxFHDabICg5t3Fs/qgRXUgo5G51bFMZyrFqOdilocash9EhhJmXxf4ON2UY/Z/IDCR8VEGgLfI2Pg+Mbk7EkJMlePnQxxt3Tf8vvzlWIjAHRVaCo3MaOFZPfKlwoeYFBsyplUKfpR3//EhA4BNhj+Vo1vKsZ7W8bM6A6sJVl81z2qNSwrC9nB7ke+5KrKUh8TBsb5B5M7JEOQGEki1kuxZar8sux91LRW2TUdqPwKbvm8vQea2rldJoDA5qNvzDJu9HpMjFg5OJjQw3sKMFo09z3Kxa543P/s/FZc0fKQikkCWpIr3xRDuTZ6+/fu5FQIp6FYCXe7Gz6MN+FuQuIMinMtXPE4JGZVsugSmQkOxLsu/+IFuD6VEiHsr7v0LQWAAbwdBYH3xbrj8eMXg3GVUtdZCm6M3lnIS0PFsloMIte32NyNtua6bpbC4bVBZn+djkztKQHpW+5ft7SR+k+a/kgS2uSvSVpVCQd4JxfnSQsU9x5QywvZEYievxJwPQYU3tJXfS9n/W3BjI7o8GjzBX/3WsRE/8Rpx3vHLBaTUtob63BOHS+oh0BU6AuQzPKYUI0Ni5ot72noL5a1B2RmjDF8VR3tNb8=
  file:
    - "$APPNAME-v$VERSION-linux-amd64"
    - "$APPNAME-v$VERSION-darwin-amd64"
    - "$APPNAME-v$VERSION-windows-amd64.exe"
  skip_cleanup: true # 因为我要上传可执行文件到 release，所以不能自动把这个文件清除
  on: # 只有打 tag 时才运行 deploy 阶段
    tags: true